"""rename department

Revision ID: df9c3eb09c55
Revises: 63d8dc88fe3c
Create Date: 2024-04-23 15:53:08.973505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9c3eb09c55'
down_revision = '63d8dc88fe3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
